# Generated by Django 5.2.7 on 2025-11-03 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.IntegerField()),
                ('instrumento', models.CharField(max_length=3)),
                ('fecha_pago', models.DateField()),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercadoCalificacion', to='datos.mercado')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origenCalificacion', to='datos.origen')),
            ],
        ),
    ]
