# Generated by Django 5.2.8 on 2025-11-19 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.IntegerField()),
                ('instrumento', models.CharField(max_length=3)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('periodo', models.IntegerField(default=0)),
                ('secuencia_evento', models.IntegerField(default=0)),
                ('factor_actualizacion', models.IntegerField(default=0)),
                ('dividendo', models.IntegerField(default=0)),
                ('valor_historico', models.FloatField(default=0.0)),
                ('fechaActualizacion', models.DateField(blank=True, null=True)),
                ('anio', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercadoCalificacion', to='datos.mercado')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origenCalificacion', to='datos.origen')),
            ],
        ),
    ]
