# Generated by Django 4.2.24 on 2025-11-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercado',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='origen',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
