# Generated by Django 5.2.8 on 2025-11-21 16:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950)])),
                ('instrumento', models.CharField(max_length=3)),
                ('fecha_pago', models.DateField()),
                ('periodo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('secuencia_evento', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('factor_actualizacion', models.IntegerField(default=0)),
                ('dividendo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_historico', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fechaActualizacion', models.DateField()),
                ('anio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2025)], verbose_name='Año')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('factores', models.JSONField(default=list)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mercado_calificacion', to='datos.mercado')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origen_calificacion', to='datos.origen')),
            ],
            options={
                'ordering': ['-instrumento', 'periodo'],
            },
        ),
    ]
